[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "rpp-cli"
version = "0.1.0"
description = "RPP command line interface"

[project.scripts]
rpp = "rpp_cli.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["rpp_cli", "rpp_cli.*"]
